### ISSUE TITLE
Binary files under source control

### ISSUE THREAD

**Issue by mkwork** [sserdyuk1991/FishnetSimulation#1]
https://github.com/sserdyuk1991/FishnetSimulation/blob/master/FishnetSimulation/FishnetSimulation.v12.suo

VS garbage under source control

**Comment by sserdyuk1991** [comment]
Do you mean that including project info files into repository is a bad practice?

**Comment by mkwork** [comment]
Yep. Any concrete user environment files. Like a property sheets or user options.
[proof (read first line)](https://msdn.microsoft.com/en-us/library/bb165909.aspx)
Also binaries.

Code base should contain source code, documentation (its sources, or plain text), build system scripts and may be  some test data (if it's necessary for tests and it's to expensive to generate it).

It's should be buildable on any clean environment which satisfies given requirements (vs2013 in your case).

**Comment by sserdyuk1991** [comment]
Thanks. I'll take a note.
